before:
  hooks:
    - go mod download

builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '5'
      - '6'
      - '7'
  - id: win
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    goarm:
      - '5'
      - '6'
      - '7'
  - id: darwin
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '5'
      - '6'
      - '7'
archives:
  - replacements:
      386: amd32
      darwin: macOS
      linux: linux

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: oui
    homepage: https://github.com/thatmattlove/oui
    description: MAC Address CLI Toolkit
    license: BSD-3-Clause-Clear
    tap:
      owner: thatmattlove
      name: homebrew-oui
      token: '{{ .Env.TAP_GITHUB_TOKEN }}'
    post_install: |
      system "oui", "update"

nfpms:
  - id: packages
    homepage: https://github.com/thatmattlove/oui
    maintainer: Matt Love <matt@stunninglyclear.com>
    description: MAC Address CLI Toolkit
    license: BSD-3-Clause-Clear
    builds:
      - linux
    replacements:
      386: amd32
      darwin: macOS
      linux: linux
    formats:
      - apk
      - deb
      - rpm
    scripts:
      postinstall: 'scripts/linux_postinstall.sh'

publishers:
  - name: fury.io
    ids:
      - packages
    dir: '{{ dir .ArtifactPath }}'
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/thatmattlove/
