before:
  hooks:
    - go mod download

builds:
  - id: nix
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '5'
      - '6'
      - '7'
  - id: win
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
    goarm:
      - '5'
      - '6'
      - '7'
  - id: darwin
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '5'
      - '6'
      - '7'
archives:
  - replacements:
      386: amd32
      darwin: macOS
      linux: linux

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: oui
    tap:
      owner: thatmattlove
      name: homebrew-oui
      token: '{{ .Env.TAP_GITHUB_TOKEN }}'
    homepage: https://github.com/thatmattlove/oui
    description: CLI tool for MAC Addresses.
    license: BSD-3-Clause-Clear
    post_install: |
      system "oui", "update"

nfpms:
  - id: packages
    file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'

publishers:
  - name: fury.io
    ids:
      - packages
    dir: '{{ dir .ArtifactPath }}'
    cmd: curl -F package=@{{ .ArtifactPath }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/thatmattlove/
