name: test

on:
    - push
    - pull_request

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Go Setup
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20

            - name: Run Tests
              run: go test -v ./...
