name: test

on:
    - push
    - pull_request

jobs:
    test:
        strategy:
            matrix:
                go-version:
                    - 1.20.x
                os: [ubuntu-latest]
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_PASSWORD: postgres
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 5432:5432
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Setup Postgres
              run: |
                  psql postgres -c 'CREATE DATABASE oui;'
                  psql postgres -c 'CREATE USER oui WITH PASSWORD "oui";'
                  psql postgres -c 'ALTER DATABASE oui OWNER TO oui;'

            - name: Go Setup
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ matrix.go-version }}

            - name: Run Tests
              run: go test -v ./...
              env:
                  POSTGRES_PASSWORD: oui
